### ISSUE TITLE
Recommend setting default enabled setting to false

### ISSUE THREAD

**Issue by MartyBAus** [bleutzinn/grav-plugin-snitch#1]
While the snitch plugin: https://github.com/bleutzinn/grav-plugin-snitch from @bleutzinn is a very useful tool for development purposes, I discovered a pattern of use which can unexpectedly reveal all a website's parameters, including all the user details and possibly sensitive information to the internet. This stems from the default snitch setting "enabled: true".

1. Build a Grav website
2. Install the snitch plugin
3. Create an environment configuration area under user/ eg. user/localhost
4. Create an environment configuration for the main production website, eg. user/www.widgets.com
5. Disable the snitch plugin on the www.widget.com environment

Note that although the snitch plugin is now apparently disabled on the production website, it is enabled in the localhost and default settings. Many hosting arrangements will permit requests to main.com as well as to www.main.com. http://main.com will use the default settings so internet browsers accessing http://main.com will see all the Grav parameters.

I suggest that the snitch source setting be changed to "enabled: false" to avoid this scenario. Users should be advised to enable the plugin for their specific dev environment, but not in the default settings. It is generally good security practice to have default settings for parameters which could be security concerns to "disabled".

Regards,
Martin

**Comment by bleutzinn** [comment]
Hi Martin,

Thanks for pointing this out.

I do agree that setting `enabled` to `false` is an improvement and I'll make that change a.s.a.p.   
However isn't it a good practice as well to keep a dev environment separate from your production environment. Your scenario though possible seems rather far fetched. Besides which information will be shown on a website depends on which variables the developer exposes through Twig templates.

Or am I overlooking something?

**Comment by MartyBAus** [comment]
Thanks for the reply. Possibly far fetched yes, but it happened recently on a site I'm a member of. All the member details could be seen on the website when the URL without a www was used.

Good practice would be to not use snitch on a production website, I agree. But Grav does provide the capability to have different environment configurations in the one bundle.

Using just the basic Grav skeleton plus snitch created the issue so there's no particular twig coding or changes required.

Regards,
Martin

**Comment by bleutzinn** [comment]
As you may have seen the default plugin setting is now false.

Just to satisfy my curiosity, how can user data be visible in a web page by not logged in users without using the Twig variables with user data which this plugin creates.

**Comment by MartyBAus** [comment]
Hi Ron,

I'm by no means a Grav expert although I have tinkered with my own custom
plugins. All I had to do to see the behaviour was:

   1. Unzip the basic grav package and the admin package:
   unzip ../grav-v1.7.37.1.zip
   unzip ../grav-admin-v1.7.29.1.zip
   2. Install the snitch plugin and enable it
   3. Create a user and a group
   4. Access the default homepage (without any login or session) to see:
   [image: image.png]

Maybe there's something more going on but it seems that nothing is required
to the default skeleton to reproduce the behaviour.

Cheers,
Martin

**Comment by bleutzinn** [comment]
One final request. Could you please try again and add your screenshot ("image.png") to this issue here in GitHub or make it available online somehow for everyone to see? Thanks!

**Comment by MartyBAus** [comment]
Example of information view:
![image](https://user-images.githubusercontent.com/119151579/204654446-7ff83437-e253-4d7e-8a8d-6b0b24d1cc77.png)

**Comment by bleutzinn** [comment]
Thanks for posting the image.

Clearly this plugin was intended for my own use only. I have removed the `dump` commands so the user and group data isn't shown anymore.

PS I have hidden your image as it revealed some private information.
